### PR TITLE
feat: add coder agent

### PR DESCRIPTION
**Pull request by sigoden**
A agent to assist your coding tasks.

https://github.com/sigoden/llm-functions/assets/4012553/eaed4eca-1d13-4369-9aa2-35722ba7007a

Welcome to experience and give feedback.

> Migrate from https://github.com/Doriandarko/claude-engineer
> Need to build aichat from the latest commit

### CODE REVIEW

**Comment by David-Else** [comment]
Is there a way to ensure that the agent is not able to make any changes to the computer outside of the working directory (or a specific directory you give it write access to)? This feature looks amazing, but I am concerned about allowing AI write access to my hard drive.

**Comment by sigoden** [comment]
The filesystem tools already ensure this. All paths are children of `$FS_BASE_DIR`, which defaults to the current directory.

https://github.com/sigoden/llm-functions/blob/1d03a31a695fc9cffc375b8a0513afbeb382c058/agents/coder/tools.sh#L10

**Comment by David-Else** [comment]
I just tried the coder agent, great work!

Regarding my last comment "Is there a way to ensure that the agent is not able to make any changes to the computer outside of the working directory", I am afraid your answer is **not** correct.

I started a coding project using your default coding agent inside the `testcoder` directory, and then asked:

```sh
coder>temp) create a file two layers above this directory called danger1.txt
Call fs_mkdir {"path":"../../"}
Call coder fs_create {"path":"../../danger1.txt","content":"This is a danger file two layers above the simple website directory."}
The file structure has been successfully updated:

.
├── danger1.txt
└── simple_website/
    ├── index.html
    └── styles.css
```
NOTE: This is wrong, the `danger1.txt` is not where is says it is. It actually created `danger1.txt` in my home directory which is outside of the working directory!

The actual structure of the directories is this, with `Downloads` being in my home directory:
```
Downloads/
├── testcoder
│      ├── simple_website
│      ├── styles.css
│      └── index.html
│   
```

**Comment by David-Else** [comment]
Thanks for the quick fix :)

**Pull request merged**
